config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :libros 
  
  
    delete 'libros/' => 'libros#destroy_batch'

end

app/models/input_from_file.rb
module InputFromFile

require 'csv'

# Este metodo es ajeno a los nombre de las columnas.
#
# De momento no hay ningun tipo de sanity check. 
# (asume que el csv tiene tantas columnas como columnas
# tiene la tabla 'libro')
def Libro.load_from_csv 


  # test file
  filename = "#{Rails.root}/public/csv/input.csv"
  CSV.foreach(filename) do |row|
    
    record = Libro.record_hash(row)
    Libro.create(record)
  end
end


def Libro.record_hash array_records

  # devuelve un array de strings con los nombres de las columnas, 
  # excepto:  - "id"
  #           - "created_at"
  #           - "update_at" 
  column_names = Libro.column_names
  keys = column_names.drop(1).take(column_names.size-3)
  
  # crea el hash keys ==> array_records
  if array_records.length == keys.length
    
    keys.zip(array_records).to_h
    
  end

end

end

app/models/libro.rb
class Libro < ActiveRecord::Base

### CLASS METHODS

extend InputFromFile

### INSTANCE METHODS


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController

def index

@libros = Libro.all
end

# DELETE /libros/:id
def destroy

  libro = Libro.find(params[:id])
  
  libro.destroy!
  
  redirect_to libros_path
  
end


# POST /libros
def create

  # lee desde /public/csv/input.csv
  # y crea un record por fila.
  # 
  Libro.load_from_csv
  
  redirect_to libros_path
end

# DELETE /libros
# esta accion es solo para facilitar testing...
def destroy_batch

  Libro.all.each { |libro| libro.destroy!  }
  redirect_to libros_path
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibreTeka</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/libros/index.html.erb
<body>

<h1><center>El increible archivo de libros<center></h1> 

<%= form_tag({controller: "libros", action: "create"}, method: "POST") do %>

<%= submit_tag "Cargar archivos desde csv" %>
<% end %>

<% if @libros.empty? %>

<h2><center> No hay nigun libro en la base de datos :-( <center></h2>

<% else %>
<br><br>
<div id="destroy_all",style="right:2px;">
  <%= button_to 'Destruir todos los libros', libros_path,
                              method: :delete,
                              data: { confirm: 'Estas seguro?' } %>
 
  <br><br>
</div>


 
<table>
  <tr>
    <th></th>
    <th>Titulo</th>
    <th>Autor</th>
    <th>Editorial</th>
    <th>ISBN</th>
  </tr>
 
  <% i=1 %>
  <% @libros.each do |libro| %>
    <tr>
      <td><%= i               %></td>
      <td><%= libro.titulo    %></td>
      <td><%= libro.autor     %></td>
      <td><%= libro.editorial %></td>
      <td><%= libro.isbn      %></td>
      <td><%= link_to 'Destruir', libro_path(libro),
                              method: :delete,
                              data: { confirm: 'Estas seguro?' } %>
      </td>
     
    </tr>
  <% i=i+1 %>
  <% end %>
</table>

<% end %>

</body>

app/views/welcome/index.html.erb
<body>

<div id="cabecera">

	<div id="cabsup">
		<div id="logo">
			<br>
		<IMG SRC="logo.png" ALT="La primera biblioteca física p2p" WIDTH=300 HEIGHT=100% >

		</div>
	
	</div>


	<div id="menu">


	 <ul>
	    <li><%= link_to 'Archivo', libros_path%></li>
	    <li> link to 'Inicio'</li>
	    <li> link to '¿Cómo funciona?' </li>
	    <li> link to 'Preguntas Frecuentes' </li>
	    <li> link to 'Nuestros principios' </li>
	    <li> link to 'Contacto' </li>
	 </ul>

	</div>

</div>




<br>
<br>
<br>
<div id="principal">

	<div id="princip_izda">
	<center>
    <IMG SRC="owl-158417.png" ALT="La primera biblioteca física p2p"
     WIDTH=278 HEIGHT=100% ALIGN=middl>
     </center>
	</div>


</div>

</body>